version: "3.9"
services:
  node-data-collector:
    image: postgres
    restart: always
    container_name: node-data-collector-database
    ports:
      - 5452:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

 
volumes:
  postgres:
  rabbitmq: